version: '3'

services:
  moviesservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
