version: '3.4'

services:
  moviesservice:
    image: moviesservice
    container_name: moviesservice
    ports:
      - "5000:5000"
    build:
      context: ./MoviesService
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
#    networks:
#      - net1

  webmvc:
    image: webmvc   
    ports:
      - "5001:5001"
    build:
      context: ./WebMVC
      dockerfile: Dockerfile
    restart: always

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: zwb
      MYSQL_PASSWORD: zwb
      MYSQL_DATABASE: TestDataBase
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ONLINE_PASSWORD: 1
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
#    networks:
#      - net1

#networks:
#  net1:
#    external: true